// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fuacvxrszikgtleitoeg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ1YWN2eHJzemlrZ3RsZWl0b2VnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwMjMyNzksImV4cCI6MjA1ODU5OTI3OX0.Up6rBkJCXDov8MevYAeyVbFzQvRLvEK4Mm-CVOZUbZk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);